import os
from sqlalchemy import create_engine, text, MetaData, Table, inspect, Column, Integer, BigInteger, Text, Numeric
from sqlalchemy.orm import sessionmaker

PROD_DB_URL = "postgresql://dispet_admin_:VTCgwlOp1saQYLdv2gLeHQOVdbhvZO33@dpg-d4781ehr0fns73f9ipc0-a.oregon-postgres.render.com/db_ordersync"

engine = create_engine(PROD_DB_URL)
Session = sessionmaker(bind=engine)
session = Session()

metadata = MetaData()
# Explicit definitions to ensure casting
t_prod_v2 = Table('t_cadastro_produto_v2', metadata,
    Column('id', BigInteger, primary_key=True), # Default auto-inc
    Column('codigo_supra', Text),
    autoload_with=engine, extend_existing=True
)

def migrate_products():
    print("Fetching V1 products...")
    # Fetch V1
    stmt = text("SELECT * FROM t_cadastro_produto")
    v1_rows = session.execute(stmt).fetchall()
    print(f"Found {len(v1_rows)} V1 products.")
    
    # Fetch existing V2 codes to avoid dupes
    existing_codes = {r[0] for r in session.query(t_prod_v2.c.codigo_supra).all()}
    print(f"Found {len(existing_codes)} existing V2 products.")
    
    count = 0
    for row in v1_rows:
        r = row._mapping
        code = str(r.get('codigo_supra') or '').strip()
        
        if not code or code in existing_codes:
            continue
            
        v2_data = {
            "codigo_supra": code,
            "status_produto": r.get('status_produto') or 'ATIVO',
            "nome_produto": r.get('nome_produto') or "Produto Sem Nome",
            "unidade": r.get('unidade'),
            # 'embalagem' doesn't exist in V1? Let's check logs. Log says: 
            # codigo_supra, status_produto, tipo_giro, estoque_disponivel, nome_produto, preco, desconto, unidade, peso, cst, ipi, icms, iva_st, validade_tabela, preco_lista_supra, familia, filhos, marca, fornecedor...
            # No 'embalagem' or 'ean' or 'ncm' in V1 list.
            "embalagem_venda": None, 
            "ncm": None, 
            "codigo_ean": None,
            "marca": r.get('marca'), 
            "peso": r.get('peso') or 0,
            
            # Defaults
            "estoque_disponivel": r.get('estoque_disponivel') or 0,
            "estoque_ideal": 0,
            "preco": r.get('preco') or 0,
            "tipo": "INSUMOS" # Default assumption
        }
        
        try:
            # Let ID be auto-generated by V2 sequence (hope products have one!)
            # If products table also lacks sequence, we will fail here.
            # Let's hope. If not, we will need to fix likely.
            # Previous checks showed V2 product table has 172 rows, so likely valid.
            stmt_ins = t_prod_v2.insert().values(**v2_data)
            session.execute(stmt_ins)
            existing_codes.add(code)
            count += 1
        except Exception as e:
            print(f"Error inserting {code}: {e}")
            session.rollback()
            
    try:
        session.commit()
        print(f"Successfully migrated {count} products.")
    except Exception as e:
        session.rollback()
        print(f"Error commit: {e}")
    finally:
        session.close()

if __name__ == "__main__":
    migrate_products()
