services:
  - type: web
    name: ordersync-backend
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    env: python
    runtime: python
    pythonVersion: 3.11.9
    plan: free
    autoDeploy: true
